---
- name: "Generate named.conf.options"
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart bind9

- name: "Generate all db for zones"
  ansible.builtin.template:
    src: db.local.j2
    dest: /etc/bind/db.{{ item.name }}
    owner: root
    group: root
    mode: "0644"
  become: true
  loop: "{{ bind9_zones }}"
  when: item.master is not defined
  # We only want to create zone files if we are the master for this zone
  # and only slaves will have a master attribute
  notify: Restart bind9

- name: "Ensure directory exists for log files"
  ansible.builtin.file:
    path: /var/log/named
    state: directory
    owner: bind
    group: bind
    mode: "0700"

- name: "Generate named.conf.local"
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart bind9


- name: "Validate bind9 configuration"
  ansible.builtin.command:
    cmd: named-checkconf
  become: true
  register: named_checkconf
  failed_when: named_checkconf.rc != 0
  changed_when: false

# find to validate the configuration for db files

- name: "Ensure bind9 is running"
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true
  become: true
