---
- name: "Generate named.conf.options"
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart bind9

- name: "Generate all db for zones"
  ansible.builtin.template:
    src: db.local.j2
    dest: /etc/bind/db.{{ item.name }}
    owner: root
    group: root
    mode: "0644"
  become: true
  loop: "{{ bind9_zones }}"
  when: bind9_master_name == bind9_hostname
  notify: Restart bind9

- name: "Generate named.conf.local"
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart bind9

# todo add check for bind9_zones config

- name: "Ensure bind9 is running"
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true
  become: true
